/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthenticatedStoricoRouteImport } from './routes/_authenticated/storico'
import { Route as AuthenticatedProfiloRouteImport } from './routes/_authenticated/profilo'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSchedeIndexRouteImport } from './routes/_authenticated/schede.index'
import { Route as AuthenticatedCerchiaIndexRouteImport } from './routes/_authenticated/cerchia.index'
import { Route as AuthenticatedSchedePlanIdRouteImport } from './routes/_authenticated/schede.$planId'
import { Route as AuthenticatedCerchiaCircleIdRouteImport } from './routes/_authenticated/cerchia.$circleId'
import { Route as AuthenticatedAllenaPlanIdRouteImport } from './routes/_authenticated/allena.$planId'
import { Route as AuthenticatedAdminSetCoachRouteImport } from './routes/_authenticated/admin.set-coach'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedStoricoRoute = AuthenticatedStoricoRouteImport.update({
  id: '/storico',
  path: '/storico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfiloRoute = AuthenticatedProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedeIndexRoute =
  AuthenticatedSchedeIndexRouteImport.update({
    id: '/schede/',
    path: '/schede/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCerchiaIndexRoute =
  AuthenticatedCerchiaIndexRouteImport.update({
    id: '/cerchia/',
    path: '/cerchia/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchedePlanIdRoute =
  AuthenticatedSchedePlanIdRouteImport.update({
    id: '/schede/$planId',
    path: '/schede/$planId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCerchiaCircleIdRoute =
  AuthenticatedCerchiaCircleIdRouteImport.update({
    id: '/cerchia/$circleId',
    path: '/cerchia/$circleId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAllenaPlanIdRoute =
  AuthenticatedAllenaPlanIdRouteImport.update({
    id: '/allena/$planId',
    path: '/allena/$planId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSetCoachRoute =
  AuthenticatedAdminSetCoachRouteImport.update({
    id: '/admin/set-coach',
    path: '/admin/set-coach',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/storico': typeof AuthenticatedStoricoRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/': typeof AuthIndexRoute
  '/admin/set-coach': typeof AuthenticatedAdminSetCoachRoute
  '/allena/$planId': typeof AuthenticatedAllenaPlanIdRoute
  '/cerchia/$circleId': typeof AuthenticatedCerchiaCircleIdRoute
  '/schede/$planId': typeof AuthenticatedSchedePlanIdRoute
  '/cerchia/': typeof AuthenticatedCerchiaIndexRoute
  '/schede/': typeof AuthenticatedSchedeIndexRoute
}
export interface FileRoutesByTo {
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profilo': typeof AuthenticatedProfiloRoute
  '/storico': typeof AuthenticatedStoricoRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthIndexRoute
  '/admin/set-coach': typeof AuthenticatedAdminSetCoachRoute
  '/allena/$planId': typeof AuthenticatedAllenaPlanIdRoute
  '/cerchia/$circleId': typeof AuthenticatedCerchiaCircleIdRoute
  '/schede/$planId': typeof AuthenticatedSchedePlanIdRoute
  '/cerchia': typeof AuthenticatedCerchiaIndexRoute
  '/schede': typeof AuthenticatedSchedeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profilo': typeof AuthenticatedProfiloRoute
  '/_authenticated/storico': typeof AuthenticatedStoricoRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/admin/set-coach': typeof AuthenticatedAdminSetCoachRoute
  '/_authenticated/allena/$planId': typeof AuthenticatedAllenaPlanIdRoute
  '/_authenticated/cerchia/$circleId': typeof AuthenticatedCerchiaCircleIdRoute
  '/_authenticated/schede/$planId': typeof AuthenticatedSchedePlanIdRoute
  '/_authenticated/cerchia/': typeof AuthenticatedCerchiaIndexRoute
  '/_authenticated/schede/': typeof AuthenticatedSchedeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/profilo'
    | '/storico'
    | '/auth/reset'
    | '/auth/verify'
    | '/auth/'
    | '/admin/set-coach'
    | '/allena/$planId'
    | '/cerchia/$circleId'
    | '/schede/$planId'
    | '/cerchia/'
    | '/schede/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/onboarding'
    | '/profilo'
    | '/storico'
    | '/auth/reset'
    | '/auth/verify'
    | '/'
    | '/auth'
    | '/admin/set-coach'
    | '/allena/$planId'
    | '/cerchia/$circleId'
    | '/schede/$planId'
    | '/cerchia'
    | '/schede'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/onboarding'
    | '/_authenticated/profilo'
    | '/_authenticated/storico'
    | '/auth/reset'
    | '/auth/verify'
    | '/_authenticated/'
    | '/auth/'
    | '/_authenticated/admin/set-coach'
    | '/_authenticated/allena/$planId'
    | '/_authenticated/cerchia/$circleId'
    | '/_authenticated/schede/$planId'
    | '/_authenticated/cerchia/'
    | '/_authenticated/schede/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/storico': {
      id: '/_authenticated/storico'
      path: '/storico'
      fullPath: '/storico'
      preLoaderRoute: typeof AuthenticatedStoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profilo': {
      id: '/_authenticated/profilo'
      path: '/profilo'
      fullPath: '/profilo'
      preLoaderRoute: typeof AuthenticatedProfiloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schede/': {
      id: '/_authenticated/schede/'
      path: '/schede'
      fullPath: '/schede/'
      preLoaderRoute: typeof AuthenticatedSchedeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cerchia/': {
      id: '/_authenticated/cerchia/'
      path: '/cerchia'
      fullPath: '/cerchia/'
      preLoaderRoute: typeof AuthenticatedCerchiaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schede/$planId': {
      id: '/_authenticated/schede/$planId'
      path: '/schede/$planId'
      fullPath: '/schede/$planId'
      preLoaderRoute: typeof AuthenticatedSchedePlanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cerchia/$circleId': {
      id: '/_authenticated/cerchia/$circleId'
      path: '/cerchia/$circleId'
      fullPath: '/cerchia/$circleId'
      preLoaderRoute: typeof AuthenticatedCerchiaCircleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/allena/$planId': {
      id: '/_authenticated/allena/$planId'
      path: '/allena/$planId'
      fullPath: '/allena/$planId'
      preLoaderRoute: typeof AuthenticatedAllenaPlanIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/set-coach': {
      id: '/_authenticated/admin/set-coach'
      path: '/admin/set-coach'
      fullPath: '/admin/set-coach'
      preLoaderRoute: typeof AuthenticatedAdminSetCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfiloRoute: typeof AuthenticatedProfiloRoute
  AuthenticatedStoricoRoute: typeof AuthenticatedStoricoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminSetCoachRoute: typeof AuthenticatedAdminSetCoachRoute
  AuthenticatedAllenaPlanIdRoute: typeof AuthenticatedAllenaPlanIdRoute
  AuthenticatedCerchiaCircleIdRoute: typeof AuthenticatedCerchiaCircleIdRoute
  AuthenticatedSchedePlanIdRoute: typeof AuthenticatedSchedePlanIdRoute
  AuthenticatedCerchiaIndexRoute: typeof AuthenticatedCerchiaIndexRoute
  AuthenticatedSchedeIndexRoute: typeof AuthenticatedSchedeIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfiloRoute: AuthenticatedProfiloRoute,
  AuthenticatedStoricoRoute: AuthenticatedStoricoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminSetCoachRoute: AuthenticatedAdminSetCoachRoute,
  AuthenticatedAllenaPlanIdRoute: AuthenticatedAllenaPlanIdRoute,
  AuthenticatedCerchiaCircleIdRoute: AuthenticatedCerchiaCircleIdRoute,
  AuthenticatedSchedePlanIdRoute: AuthenticatedSchedePlanIdRoute,
  AuthenticatedCerchiaIndexRoute: AuthenticatedCerchiaIndexRoute,
  AuthenticatedSchedeIndexRoute: AuthenticatedSchedeIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
