/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AppStoricoRouteImport } from './routes/app/storico'
import { Route as AppProfiloRouteImport } from './routes/app/profilo'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppSchedeIndexRouteImport } from './routes/app/schede.index'
import { Route as AppCerchiaIndexRouteImport } from './routes/app/cerchia.index'
import { Route as AppAdminIndexRouteImport } from './routes/app/admin.index'
import { Route as AppSchedePlanIdRouteImport } from './routes/app/schede.$planId'
import { Route as AppCerchiaCircleIdRouteImport } from './routes/app/cerchia.$circleId'
import { Route as AppAllenaPlanIdRouteImport } from './routes/app/allena.$planId'
import { Route as AppAdminUserStoricoRouteImport } from './routes/app/admin.user-storico'
import { Route as AppAdminSetCoachRouteImport } from './routes/app/admin.set-coach'
import { Route as AppAdminUserUserIdRouteImport } from './routes/app/admin.user.$userId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AppStoricoRoute = AppStoricoRouteImport.update({
  id: '/storico',
  path: '/storico',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfiloRoute = AppProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchedeIndexRoute = AppSchedeIndexRouteImport.update({
  id: '/schede/',
  path: '/schede/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCerchiaIndexRoute = AppCerchiaIndexRouteImport.update({
  id: '/cerchia/',
  path: '/cerchia/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchedePlanIdRoute = AppSchedePlanIdRouteImport.update({
  id: '/schede/$planId',
  path: '/schede/$planId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCerchiaCircleIdRoute = AppCerchiaCircleIdRouteImport.update({
  id: '/cerchia/$circleId',
  path: '/cerchia/$circleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAllenaPlanIdRoute = AppAllenaPlanIdRouteImport.update({
  id: '/allena/$planId',
  path: '/allena/$planId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUserStoricoRoute = AppAdminUserStoricoRouteImport.update({
  id: '/admin/user-storico',
  path: '/admin/user-storico',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminSetCoachRoute = AppAdminSetCoachRouteImport.update({
  id: '/admin/set-coach',
  path: '/admin/set-coach',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAdminUserUserIdRoute = AppAdminUserUserIdRouteImport.update({
  id: '/admin/user/$userId',
  path: '/admin/user/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profilo': typeof AppProfiloRoute
  '/app/storico': typeof AppStoricoRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin/set-coach': typeof AppAdminSetCoachRoute
  '/app/admin/user-storico': typeof AppAdminUserStoricoRoute
  '/app/allena/$planId': typeof AppAllenaPlanIdRoute
  '/app/cerchia/$circleId': typeof AppCerchiaCircleIdRoute
  '/app/schede/$planId': typeof AppSchedePlanIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/cerchia/': typeof AppCerchiaIndexRoute
  '/app/schede/': typeof AppSchedeIndexRoute
  '/app/admin/user/$userId': typeof AppAdminUserUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profilo': typeof AppProfiloRoute
  '/app/storico': typeof AppStoricoRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/app/admin/set-coach': typeof AppAdminSetCoachRoute
  '/app/admin/user-storico': typeof AppAdminUserStoricoRoute
  '/app/allena/$planId': typeof AppAllenaPlanIdRoute
  '/app/cerchia/$circleId': typeof AppCerchiaCircleIdRoute
  '/app/schede/$planId': typeof AppSchedePlanIdRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/cerchia': typeof AppCerchiaIndexRoute
  '/app/schede': typeof AppSchedeIndexRoute
  '/app/admin/user/$userId': typeof AppAdminUserUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profilo': typeof AppProfiloRoute
  '/app/storico': typeof AppStoricoRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin/set-coach': typeof AppAdminSetCoachRoute
  '/app/admin/user-storico': typeof AppAdminUserStoricoRoute
  '/app/allena/$planId': typeof AppAllenaPlanIdRoute
  '/app/cerchia/$circleId': typeof AppCerchiaCircleIdRoute
  '/app/schede/$planId': typeof AppSchedePlanIdRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/cerchia/': typeof AppCerchiaIndexRoute
  '/app/schede/': typeof AppSchedeIndexRoute
  '/app/admin/user/$userId': typeof AppAdminUserUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/onboarding'
    | '/app/profilo'
    | '/app/storico'
    | '/auth/reset'
    | '/auth/verify'
    | '/app/'
    | '/auth/'
    | '/app/admin/set-coach'
    | '/app/admin/user-storico'
    | '/app/allena/$planId'
    | '/app/cerchia/$circleId'
    | '/app/schede/$planId'
    | '/app/admin/'
    | '/app/cerchia/'
    | '/app/schede/'
    | '/app/admin/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/onboarding'
    | '/app/profilo'
    | '/app/storico'
    | '/auth/reset'
    | '/auth/verify'
    | '/app'
    | '/auth'
    | '/app/admin/set-coach'
    | '/app/admin/user-storico'
    | '/app/allena/$planId'
    | '/app/cerchia/$circleId'
    | '/app/schede/$planId'
    | '/app/admin'
    | '/app/cerchia'
    | '/app/schede'
    | '/app/admin/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/onboarding'
    | '/app/profilo'
    | '/app/storico'
    | '/auth/reset'
    | '/auth/verify'
    | '/app/'
    | '/auth/'
    | '/app/admin/set-coach'
    | '/app/admin/user-storico'
    | '/app/allena/$planId'
    | '/app/cerchia/$circleId'
    | '/app/schede/$planId'
    | '/app/admin/'
    | '/app/cerchia/'
    | '/app/schede/'
    | '/app/admin/user/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/storico': {
      id: '/app/storico'
      path: '/storico'
      fullPath: '/app/storico'
      preLoaderRoute: typeof AppStoricoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profilo': {
      id: '/app/profilo'
      path: '/profilo'
      fullPath: '/app/profilo'
      preLoaderRoute: typeof AppProfiloRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schede/': {
      id: '/app/schede/'
      path: '/schede'
      fullPath: '/app/schede/'
      preLoaderRoute: typeof AppSchedeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cerchia/': {
      id: '/app/cerchia/'
      path: '/cerchia'
      fullPath: '/app/cerchia/'
      preLoaderRoute: typeof AppCerchiaIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/admin'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schede/$planId': {
      id: '/app/schede/$planId'
      path: '/schede/$planId'
      fullPath: '/app/schede/$planId'
      preLoaderRoute: typeof AppSchedePlanIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cerchia/$circleId': {
      id: '/app/cerchia/$circleId'
      path: '/cerchia/$circleId'
      fullPath: '/app/cerchia/$circleId'
      preLoaderRoute: typeof AppCerchiaCircleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/allena/$planId': {
      id: '/app/allena/$planId'
      path: '/allena/$planId'
      fullPath: '/app/allena/$planId'
      preLoaderRoute: typeof AppAllenaPlanIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/user-storico': {
      id: '/app/admin/user-storico'
      path: '/admin/user-storico'
      fullPath: '/app/admin/user-storico'
      preLoaderRoute: typeof AppAdminUserStoricoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/set-coach': {
      id: '/app/admin/set-coach'
      path: '/admin/set-coach'
      fullPath: '/app/admin/set-coach'
      preLoaderRoute: typeof AppAdminSetCoachRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/admin/user/$userId': {
      id: '/app/admin/user/$userId'
      path: '/admin/user/$userId'
      fullPath: '/app/admin/user/$userId'
      preLoaderRoute: typeof AppAdminUserUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfiloRoute: typeof AppProfiloRoute
  AppStoricoRoute: typeof AppStoricoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminSetCoachRoute: typeof AppAdminSetCoachRoute
  AppAdminUserStoricoRoute: typeof AppAdminUserStoricoRoute
  AppAllenaPlanIdRoute: typeof AppAllenaPlanIdRoute
  AppCerchiaCircleIdRoute: typeof AppCerchiaCircleIdRoute
  AppSchedePlanIdRoute: typeof AppSchedePlanIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppCerchiaIndexRoute: typeof AppCerchiaIndexRoute
  AppSchedeIndexRoute: typeof AppSchedeIndexRoute
  AppAdminUserUserIdRoute: typeof AppAdminUserUserIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfiloRoute: AppProfiloRoute,
  AppStoricoRoute: AppStoricoRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminSetCoachRoute: AppAdminSetCoachRoute,
  AppAdminUserStoricoRoute: AppAdminUserStoricoRoute,
  AppAllenaPlanIdRoute: AppAllenaPlanIdRoute,
  AppCerchiaCircleIdRoute: AppCerchiaCircleIdRoute,
  AppSchedePlanIdRoute: AppSchedePlanIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppCerchiaIndexRoute: AppCerchiaIndexRoute,
  AppSchedeIndexRoute: AppSchedeIndexRoute,
  AppAdminUserUserIdRoute: AppAdminUserUserIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
