/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AppStoricoRouteImport } from './routes/app/storico'
import { Route as AppProfiloRouteImport } from './routes/app/profilo'
import { Route as AppPrRouteImport } from './routes/app/pr'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppHeatmapRouteImport } from './routes/app/heatmap'
import { Route as AppSchedeIndexRouteImport } from './routes/app/schede.index'
import { Route as AppCerchiaIndexRouteImport } from './routes/app/cerchia.index'
import { Route as AppSchedePlanIdRouteImport } from './routes/app/schede.$planId'
import { Route as AppProfiloImpostazioniRouteImport } from './routes/app/profilo.impostazioni'
import { Route as AppProfiloDownloadRouteImport } from './routes/app/profilo.download'
import { Route as AppProfiloAccountRouteImport } from './routes/app/profilo.account'
import { Route as AppCerchiaCircleIdRouteImport } from './routes/app/cerchia.$circleId'
import { Route as AppAllenaPlanIdRouteImport } from './routes/app/allena.$planId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AppStoricoRoute = AppStoricoRouteImport.update({
  id: '/storico',
  path: '/storico',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfiloRoute = AppProfiloRouteImport.update({
  id: '/profilo',
  path: '/profilo',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrRoute = AppPrRouteImport.update({
  id: '/pr',
  path: '/pr',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHeatmapRoute = AppHeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchedeIndexRoute = AppSchedeIndexRouteImport.update({
  id: '/schede/',
  path: '/schede/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCerchiaIndexRoute = AppCerchiaIndexRouteImport.update({
  id: '/cerchia/',
  path: '/cerchia/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSchedePlanIdRoute = AppSchedePlanIdRouteImport.update({
  id: '/schede/$planId',
  path: '/schede/$planId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfiloImpostazioniRoute = AppProfiloImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AppProfiloRoute,
} as any)
const AppProfiloDownloadRoute = AppProfiloDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => AppProfiloRoute,
} as any)
const AppProfiloAccountRoute = AppProfiloAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppProfiloRoute,
} as any)
const AppCerchiaCircleIdRoute = AppCerchiaCircleIdRouteImport.update({
  id: '/cerchia/$circleId',
  path: '/cerchia/$circleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAllenaPlanIdRoute = AppAllenaPlanIdRouteImport.update({
  id: '/allena/$planId',
  path: '/allena/$planId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/heatmap': typeof AppHeatmapRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pr': typeof AppPrRoute
  '/app/profilo': typeof AppProfiloRouteWithChildren
  '/app/storico': typeof AppStoricoRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/allena/$planId': typeof AppAllenaPlanIdRoute
  '/app/cerchia/$circleId': typeof AppCerchiaCircleIdRoute
  '/app/profilo/account': typeof AppProfiloAccountRoute
  '/app/profilo/download': typeof AppProfiloDownloadRoute
  '/app/profilo/impostazioni': typeof AppProfiloImpostazioniRoute
  '/app/schede/$planId': typeof AppSchedePlanIdRoute
  '/app/cerchia/': typeof AppCerchiaIndexRoute
  '/app/schede/': typeof AppSchedeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/heatmap': typeof AppHeatmapRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pr': typeof AppPrRoute
  '/app/profilo': typeof AppProfiloRouteWithChildren
  '/app/storico': typeof AppStoricoRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/app/allena/$planId': typeof AppAllenaPlanIdRoute
  '/app/cerchia/$circleId': typeof AppCerchiaCircleIdRoute
  '/app/profilo/account': typeof AppProfiloAccountRoute
  '/app/profilo/download': typeof AppProfiloDownloadRoute
  '/app/profilo/impostazioni': typeof AppProfiloImpostazioniRoute
  '/app/schede/$planId': typeof AppSchedePlanIdRoute
  '/app/cerchia': typeof AppCerchiaIndexRoute
  '/app/schede': typeof AppSchedeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/heatmap': typeof AppHeatmapRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/pr': typeof AppPrRoute
  '/app/profilo': typeof AppProfiloRouteWithChildren
  '/app/storico': typeof AppStoricoRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/app/allena/$planId': typeof AppAllenaPlanIdRoute
  '/app/cerchia/$circleId': typeof AppCerchiaCircleIdRoute
  '/app/profilo/account': typeof AppProfiloAccountRoute
  '/app/profilo/download': typeof AppProfiloDownloadRoute
  '/app/profilo/impostazioni': typeof AppProfiloImpostazioniRoute
  '/app/schede/$planId': typeof AppSchedePlanIdRoute
  '/app/cerchia/': typeof AppCerchiaIndexRoute
  '/app/schede/': typeof AppSchedeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/app/heatmap'
    | '/app/onboarding'
    | '/app/pr'
    | '/app/profilo'
    | '/app/storico'
    | '/auth/reset'
    | '/auth/verify'
    | '/admin/'
    | '/app/'
    | '/auth/'
    | '/app/allena/$planId'
    | '/app/cerchia/$circleId'
    | '/app/profilo/account'
    | '/app/profilo/download'
    | '/app/profilo/impostazioni'
    | '/app/schede/$planId'
    | '/app/cerchia/'
    | '/app/schede/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/heatmap'
    | '/app/onboarding'
    | '/app/pr'
    | '/app/profilo'
    | '/app/storico'
    | '/auth/reset'
    | '/auth/verify'
    | '/admin'
    | '/app'
    | '/auth'
    | '/app/allena/$planId'
    | '/app/cerchia/$circleId'
    | '/app/profilo/account'
    | '/app/profilo/download'
    | '/app/profilo/impostazioni'
    | '/app/schede/$planId'
    | '/app/cerchia'
    | '/app/schede'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/app/heatmap'
    | '/app/onboarding'
    | '/app/pr'
    | '/app/profilo'
    | '/app/storico'
    | '/auth/reset'
    | '/auth/verify'
    | '/admin/'
    | '/app/'
    | '/auth/'
    | '/app/allena/$planId'
    | '/app/cerchia/$circleId'
    | '/app/profilo/account'
    | '/app/profilo/download'
    | '/app/profilo/impostazioni'
    | '/app/schede/$planId'
    | '/app/cerchia/'
    | '/app/schede/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/storico': {
      id: '/app/storico'
      path: '/storico'
      fullPath: '/app/storico'
      preLoaderRoute: typeof AppStoricoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profilo': {
      id: '/app/profilo'
      path: '/profilo'
      fullPath: '/app/profilo'
      preLoaderRoute: typeof AppProfiloRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/pr': {
      id: '/app/pr'
      path: '/pr'
      fullPath: '/app/pr'
      preLoaderRoute: typeof AppPrRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/heatmap': {
      id: '/app/heatmap'
      path: '/heatmap'
      fullPath: '/app/heatmap'
      preLoaderRoute: typeof AppHeatmapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schede/': {
      id: '/app/schede/'
      path: '/schede'
      fullPath: '/app/schede/'
      preLoaderRoute: typeof AppSchedeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/cerchia/': {
      id: '/app/cerchia/'
      path: '/cerchia'
      fullPath: '/app/cerchia/'
      preLoaderRoute: typeof AppCerchiaIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/schede/$planId': {
      id: '/app/schede/$planId'
      path: '/schede/$planId'
      fullPath: '/app/schede/$planId'
      preLoaderRoute: typeof AppSchedePlanIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profilo/impostazioni': {
      id: '/app/profilo/impostazioni'
      path: '/impostazioni'
      fullPath: '/app/profilo/impostazioni'
      preLoaderRoute: typeof AppProfiloImpostazioniRouteImport
      parentRoute: typeof AppProfiloRoute
    }
    '/app/profilo/download': {
      id: '/app/profilo/download'
      path: '/download'
      fullPath: '/app/profilo/download'
      preLoaderRoute: typeof AppProfiloDownloadRouteImport
      parentRoute: typeof AppProfiloRoute
    }
    '/app/profilo/account': {
      id: '/app/profilo/account'
      path: '/account'
      fullPath: '/app/profilo/account'
      preLoaderRoute: typeof AppProfiloAccountRouteImport
      parentRoute: typeof AppProfiloRoute
    }
    '/app/cerchia/$circleId': {
      id: '/app/cerchia/$circleId'
      path: '/cerchia/$circleId'
      fullPath: '/app/cerchia/$circleId'
      preLoaderRoute: typeof AppCerchiaCircleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/allena/$planId': {
      id: '/app/allena/$planId'
      path: '/allena/$planId'
      fullPath: '/app/allena/$planId'
      preLoaderRoute: typeof AppAllenaPlanIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppProfiloRouteChildren {
  AppProfiloAccountRoute: typeof AppProfiloAccountRoute
  AppProfiloDownloadRoute: typeof AppProfiloDownloadRoute
  AppProfiloImpostazioniRoute: typeof AppProfiloImpostazioniRoute
}

const AppProfiloRouteChildren: AppProfiloRouteChildren = {
  AppProfiloAccountRoute: AppProfiloAccountRoute,
  AppProfiloDownloadRoute: AppProfiloDownloadRoute,
  AppProfiloImpostazioniRoute: AppProfiloImpostazioniRoute,
}

const AppProfiloRouteWithChildren = AppProfiloRoute._addFileChildren(
  AppProfiloRouteChildren,
)

interface AppRouteRouteChildren {
  AppHeatmapRoute: typeof AppHeatmapRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPrRoute: typeof AppPrRoute
  AppProfiloRoute: typeof AppProfiloRouteWithChildren
  AppStoricoRoute: typeof AppStoricoRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAllenaPlanIdRoute: typeof AppAllenaPlanIdRoute
  AppCerchiaCircleIdRoute: typeof AppCerchiaCircleIdRoute
  AppSchedePlanIdRoute: typeof AppSchedePlanIdRoute
  AppCerchiaIndexRoute: typeof AppCerchiaIndexRoute
  AppSchedeIndexRoute: typeof AppSchedeIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppHeatmapRoute: AppHeatmapRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPrRoute: AppPrRoute,
  AppProfiloRoute: AppProfiloRouteWithChildren,
  AppStoricoRoute: AppStoricoRoute,
  AppIndexRoute: AppIndexRoute,
  AppAllenaPlanIdRoute: AppAllenaPlanIdRoute,
  AppCerchiaCircleIdRoute: AppCerchiaCircleIdRoute,
  AppSchedePlanIdRoute: AppSchedePlanIdRoute,
  AppCerchiaIndexRoute: AppCerchiaIndexRoute,
  AppSchedeIndexRoute: AppSchedeIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
