-- Popola exercise_library con il dataset completo da esercizi.csv ~85 righe.
-- Usa nome EN e gruppo principale (come richiesto).
-- L'indice unico su lower(name) evita duplicati per nome (case‑insensitive).

-- Elimina duplicati per nome (case‑insensitive) prima di creare l'indice.
-- Tiene la riga più vecchia (created_at minimo).
DELETE FROM public.exercise_library a
USING public.exercise_library b
WHERE a.created_at > b.created_at
  AND lower(a.name) = lower(b.name);

DROP INDEX IF EXISTS exercise_library_name_unique_idx;
CREATE UNIQUE INDEX exercise_library_name_unique_idx
  ON public.exercise_library (lower(name));

INSERT INTO public.exercise_library (name, muscle_group) VALUES
  ('Squat', 'Quadricipiti'),
  ('Goblet squat', 'Quadricipiti'),
  ('Front squat', 'Quadricipiti'),
  ('Back squat', 'Quadricipiti'),
  ('Jump squat', 'Quadricipiti'),
  ('Bulgarian split squat', 'Quadricipiti'),
  ('Lunge', 'Quadricipiti'),
  ('Reverse lunge', 'Quadricipiti'),
  ('Walking lunge', 'Quadricipiti'),
  ('Curtsy lunge', 'Glutei'),
  ('Step-up', 'Quadricipiti'),
  ('Pistol squat', 'Quadricipiti'),
  ('Deadlift', 'Posteriori coscia'),
  ('Romanian deadlift', 'Posteriori coscia'),
  ('Stiff leg deadlift', 'Posteriori coscia'),
  ('Sumo deadlift', 'Glutei'),
  ('Single-leg deadlift', 'Posteriori coscia'),
  ('Hip thrust', 'Glutei'),
  ('Glute bridge', 'Glutei'),
  ('Single-leg glute bridge', 'Glutei'),
  ('Calf raise', 'Polpacci'),
  ('Seated calf raise', 'Polpacci'),
  ('Leg press', 'Quadricipiti'),
  ('Leg extension', 'Quadricipiti'),
  ('Leg curl', 'Posteriori coscia'),
  ('Adductor machine', 'Interno coscia'),
  ('Abductor machine', 'Glutei medio'),
  ('Wall sit', 'Quadricipiti'),
  ('Burpee', 'Full body'),
  ('Mountain climber', 'Core'),
  ('Jumping jack', 'Cardio'),
  ('High knees', 'Cardio'),
  ('Skipping', 'Cardio'),
  ('Plank', 'Core'),
  ('Side plank', 'Obliqui'),
  ('Crunch', 'Addome'),
  ('Reverse crunch', 'Addome basso'),
  ('Bicycle crunch', 'Obliqui'),
  ('Russian twist', 'Obliqui'),
  ('Sit-up', 'Addome'),
  ('Leg raise', 'Addome basso'),
  ('Hanging leg raise', 'Addome basso'),
  ('Ab wheel rollout', 'Core'),
  ('Push-up', 'Pettorali'),
  ('Incline push-up', 'Pettorali'),
  ('Decline push-up', 'Pettorali'),
  ('Diamond push-up', 'Tricipiti'),
  ('Bench press', 'Pettorali'),
  ('Dumbbell bench press', 'Pettorali'),
  ('Incline bench press', 'Pettorali superiori'),
  ('Decline bench press', 'Pettorali inferiori'),
  ('Cable fly', 'Pettorali'),
  ('Cable crossover', 'Pettorali'),
  ('Dips', 'Pettorali'),
  ('Pull-up', 'Dorsali'),
  ('Chin-up', 'Dorsali'),
  ('Lat pulldown', 'Dorsali'),
  ('Barbell row', 'Dorsali'),
  ('Dumbbell row', 'Dorsali'),
  ('Seated cable row', 'Dorsali'),
  ('T-bar row', 'Dorsali'),
  ('Face pull', 'Deltoidi posteriori'),
  ('Hyperextension', 'Lombari'),
  ('Superman', 'Lombari'),
  ('Overhead press', 'Spalle'),
  ('Shoulder press', 'Spalle'),
  ('Arnold press', 'Spalle'),
  ('Lateral raise', 'Spalle'),
  ('Front raise', 'Spalle'),
  ('Rear delt fly', 'Deltoidi posteriori'),
  ('Barbell curl', 'Bicipiti'),
  ('Dumbbell curl', 'Bicipiti'),
  ('Hammer curl', 'Bicipiti'),
  ('Preacher curl', 'Bicipiti'),
  ('Concentration curl', 'Bicipiti'),
  ('Triceps pushdown', 'Tricipiti'),
  ('Overhead triceps extension', 'Tricipiti'),
  ('Skull crusher', 'Tricipiti'),
  ('Close-grip bench press', 'Tricipiti'),
  ('Donkey kick', 'Glutei'),
  ('Fire hydrant', 'Glutei medi'),
  ('Clamshell', 'Glutei medi'),
  ('Bird dog', 'Core'),
  ('Dead bug', 'Core'),
  ('Farmer carry', 'Core')
ON CONFLICT (lower(name)) DO NOTHING;
