// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


// no-op client used when Supabase env vars are missing. Returns the same shape
// the real client returns, but with empty data — so SSR doesn't crash and the
// app degrades gracefully (auth appears logged-out, queries return null).
function makeFallbackClient(reason: string): ReturnType<typeof createClient<Database>> {
  const empty = { data: null, error: null } as const;
  const terminator: any = {
    select: () => terminator,
    insert: async () => empty,
    update: async () => empty,
    delete: async () => empty,
    upsert: async () => empty,
    eq: () => terminator,
    neq: () => terminator,
    in: () => terminator,
    gte: () => terminator,
    lte: () => terminator,
    gt: () => terminator,
    lt: () => terminator,
    is: () => terminator,
    match: () => terminator,
    or: () => terminator,
    not: () => terminator,
    filter: () => terminator,
    order: () => terminator,
    limit: () => terminator,
    range: () => terminator,
    single: async () => empty,
    maybeSingle: async () => empty,
  };
  const authApi: any = {
    getUser: async () => empty,
    getSession: async () => empty,
    getClaims: async () => empty,
    onAuthStateChange: () => ({
      data: { subscription: { unsubscribe: () => {} } },
      error: null,
    }),
    signInWithPassword: async () => ({ data: null, error: { message: reason } }),
    signUp: async () => ({ data: null, error: { message: reason } }),
    signOut: async () => empty,
    signInWithOAuth: async () => ({ data: null, error: { message: reason } }),
    resetPasswordForEmail: async () => ({ data: null, error: { message: reason } }),
  };
  return {
    auth: authApi,
    from: () => terminator,
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering); guard against
  // ReferenceError when this file is evaluated in the browser where
  // `process` is undefined.
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ||
    (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined);
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud. Falling back to a no-op client so SSR doesn't crash.`;
    console.error(`[Supabase] ${message}`);
    return makeFallbackClient(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

